#if !os(macOS)
import XCTest

extension IndexStoreDBTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexStoreDBTests = [
        ("testErrors", testErrors),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IndexStoreDBTests.__allTests__IndexStoreDBTests),
    ]
}
#endif
