//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2025 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

public import Foundation
public import IndexStoreDB_CIndexStoreDB

/// Representation of a unit file within the Index Store that can be used to read its contents.
public final class IndexStoreUnit: Sendable {
  @usableFromInline nonisolated(unsafe) let unitReader: indexstore_unit_reader_t
  @usableFromInline let library: IndexStoreLibrary

  @usableFromInline
  init(store: IndexStore, unitName: IndexStoreStringRef, library: IndexStoreLibrary) throws {
    self.library = library
    self.unitReader = try unitName.withCString { unitNameCString in
      return try library.capturingError { error in
        library.api.unit_reader_create(store.store, unitNameCString, &error)
      }
    }
  }

  /// Whether the unit represents code from the SDK instead of the project's source code.
  @inlinable
  public var isSystemUnit: Bool {
    return library.api.unit_reader_is_system_unit(unitReader)
  }

  /// Whether the unit represents a module.
  @inlinable
  public var isModuleUnit: Bool {
    return library.api.unit_reader_is_module_unit(unitReader)
  }

  /// `false` if the unit was generated by compiling the source code in release mode.
  @inlinable
  public var isDebugCompilation: Bool {
    return library.api.unit_reader_is_debug_compilation(unitReader)
  }

  /// Whether there is a `.swift`, `.cpp` etc. file in the user's project that triggered the generation of this unit.
  ///
  /// `false` for eg. indexing of Swift interfaces in the SDK or compilation of pre-compiled modules (PCMs).
  @inlinable
  public var hasMainFile: Bool {
    return library.api.unit_reader_has_main_file(unitReader)
  }

  /// The name of the compiler that produced this unit.
  @inlinable
  public var providerIdentifier: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_provider_identifier(unitReader))
      // _overrideLifetime is needed here and below because of https://github.com/swiftlang/swift/issues/85765.
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// The version of the compiler that produced this unit, if known.
  @inlinable
  public var providerVersion: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_provider_version(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// The date at which the unit file was crated.
  @inlinable
  public var modificationDate: Date {
    var seconds: Int64 = 0
    var nanoseconds: Int64 = 0
    library.api.unit_reader_get_modification_time(unitReader, &seconds, &nanoseconds)
    return Date(timeIntervalSince1970: Double(nanoseconds) / 1_000_000_000 + Double(seconds))
  }

  /// The path of the `.swift`, `.cpp` etc. file that triggered the generation of this unit.
  ///
  /// Empty if `hasMainFile` is `false`.
  @inlinable
  public var mainFile: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_main_file(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// For Swift files, the name of the module in which the source file was compiled.
  @inlinable
  public var moduleName: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_module_name(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// The working directory used during the module's compilation.
  @inlinable
  public var workingDirectory: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_working_dir(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// A path-like string that identifies the configuration in which the source file was compiled.
  ///
  /// See discussion in `Index Store.md` about what this signifies.-
  @inlinable
  public var outputFile: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_output_file(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// Path to the SDK that was used to compile this unit.
  @inlinable
  public var sysrootPath: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_sysroot_path(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// Triple of the target that was used to compile this unit.
  @inlinable
  public var target: IndexStoreStringRef {
    @_lifetime(borrow self)
    borrowing get {
      let stringRef = IndexStoreStringRef(library.api.unit_reader_get_target(unitReader))
      return _overrideLifetime(stringRef, borrowing: self)
    }
  }

  /// The dependencies of the unit.
  ///
  /// Usually, this contains one record file and unit representing the modules that were imported by this unit.
  @inlinable
  public var dependencies: IndexStoreSequence<IndexStoreUnitDependency> {
    return IndexStoreSequence { body in
      _ = iterateWithClosureAsContextToCFunctionPointer { context, handleResult in
        self.library.api.unit_reader_dependencies_apply_f(self.unitReader, context, handleResult)
      } handleResult: { result in
        return body(IndexStoreUnitDependency(dependency: result!, library: self.library))
      }
    }
  }
}
